env:
  node:        true

parser:        babel-eslint

parserOption:
  ecmaVersion: 2015
  sourceType:  module

extends:
  - 'airbnb-base'
  - plugin:import/errors
  - plugin:import/warnings

rules:
  no-console:  0
